services:
  nextjs:
    build: .
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - HOST=0.0.0.0
    command: npm run dev
    restart: unless-stopped
